# Generated by Django 5.2 on 2026-05-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="fecha_fin",
            field=models.DateField(default="2026-5-19"),
            preserve_default=False,
        ),
    ]
